final_work/urls.py
from taskmanager.views import *
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view


urlpatterns = [
    path('', redirect_view ),
    path("admin/", admin.site.urls),
    path("tasklist/", MyModelListView.as_view()),
    path("taskupdate/<int:pk>", MyModelUpdateView.as_view()),
    path("taskcreate/", MyModelCreateView.as_view()),
    path("taskdelete/<int:pk>", MyModelDeleteView.as_view()),
    path("taskdetail/<int:pk>", MyModelDetailView.as_view()),
    path("sprintlist/", SprintListView.as_view()),
    path("sprintupdate/<int:pk>", SprintUpdateView.as_view()),
    path("sprintcreate/", SprintCreateView.as_view()),
    path("sprintdelete/<int:pk>", SprintDeleteView.as_view()),
    path("sprintdetail/<int:pk>", SprintDetailView.as_view()),
    path("projectlist/", ProjectListView.as_view()),
    path("projectupdate/<int:pk>", ProjectUpdateView.as_view()),
    path("projectcreate/", ProjectCreateView.as_view()),
    path("projectdelete/<int:pk>", ProjectDeleteView.as_view()),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view()),
    path("api/", include("taskmanager.urls")),
]

taskmanager/urls.py
from rest_framework.routers import DefaultRouter
from .views import TodolistViewSet

router = DefaultRouter()
app_name = "taskmanagerapp"

router.register(
    prefix="tasks",
    viewset=TodolistViewSet,
    basename="tasks",
)
urlpatterns = router.urls

taskmanager/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
import logging
from django_extensions.db import models as ext_models

logger = logging.getLogger(__name__)
class TaskStatus(models.Model):
    status = models.CharField(max_length=150, help_text="Статус задачи")
    def __str__(self) -> str:
        return f'{self.status}'
    class Meta:
        verbose_name_plural = 'Task statuses'

class Project(ext_models.TimeStampedModel):
    name = models.CharField(max_length=250, help_text="Описание проекта")
    complete_time = models.DateTimeField(
        default=None,
        auto_now=False,
        blank=True,
        null=True,
        help_text="Время завершения проекта"
    )

    def save(self, *args, **kwargs) -> None:
        logger.warning(f'Save project "{self.name}"')
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'Project: {self.name}'
    
    class Meta:
        ordering = ["created"]

class Sprint(ext_models.TimeStampedModel):
    name = models.CharField(max_length=250, help_text="Описание спринта")
    is_active = models.BooleanField(default=True, help_text="Отметка о состоянии спринта")
    dead_line = models.DateField(
        default=None,
        null=True,
        help_text="Дата, до которой должен быть выполнен спринт"
    )
    complete_time = models.DateTimeField(
        default=None,
        auto_now=False,
        blank=True,
        null=True,
        help_text="Время завершения спринта"
    )
    project = models.ForeignKey(
        to=Project,
        on_delete=models.CASCADE,
        null=True,
        related_name='project_sprints',
        help_text='Ссылки на id проекта для спринта'
    )

    def save(self, *args, **kwargs) -> None:
        logger.warning(f'Save sprint "{self.name}"')
        if self.is_active and self.complete_time:
            self.complete_time = None
        elif not self.is_active and self.complete_time is None:
            self.complete_time = timezone.now()
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'Sprint: {self.name} | deadline {self.dead_line.strftime("%d.%m.%Y")}'
    
    class Meta:
        ordering = ["created"]

class Task(ext_models.TimeStampedModel):
    name = models.CharField(max_length=250, help_text="Описание задачи")
    dead_line = models.DateField(
        default=None,
        null=True,
        help_text="Дата, до которой должна быть выполнена задача"
    )
    complete_time = models.DateTimeField(
        default=None,
        auto_now=False,
        blank=True,
        null=True,
        help_text="Время завершения задачи"
    )
    status = models.ForeignKey(
        to=TaskStatus,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='status_tasks',
        help_text='Статус',
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='user_tasks',
        help_text='Исполнитель',
    )
    parent_task = models.ForeignKey(
        to='self',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='sub_task',
        help_text='Родительская задача'
    )
    sprint = models.ForeignKey(
        to=Sprint,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='sprint_tasks',
        help_text='Связь со спринтами'
    )

    def save(self, *args, **kwargs) -> None:
        logger.warning(f'Save task "{self.name}"')
        logger.warning(f'Save task in sprint "{self.sprint}"')
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.name} | deadline {self.dead_line.strftime("%d.%m.%Y")}'
    
    class Meta:
        ordering = ["created"]

taskmanager/forms.py
from django import forms
from taskmanager.models import Task

class ParentTaskSelect(forms.Select):
    def create_option(self, name, value, label, selected, index, subindex=None, attrs={'class': 'form-select'}):
        option = super().create_option(name, value, label, selected, index, subindex, attrs)
        if value:
            option['attrs']['name'] = value.instance.name
        return option

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'name',
            'dead_line',
            'parent_task'
        ]
        widgets = {'parent_task': ParentTaskSelect}


class CreateForm(forms.ModelForm):
    email = forms.EmailField()
    reason = forms.ChoiceField(
        choices=[("COMMENT", "Comment"), ("COMMENT", "Complaint")],
        widget=forms.Select,
        required=False,
    )
    comment = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Task
        fields = [
            'name',
            'dead_line',
            'parent_task'
        ]
        widgets = {
            'dead_line': forms.DateInput(),
            'parent_task': forms.Select(attrs={'class': "form-select"})
        }

taskmanager/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from taskmanager.models import Task, TaskStatus, Sprint, Project
from .serializers import TodoSerializer
from .filters import TodoFilterSet
from django.contrib.auth import get_user_model
from rest_framework import viewsets
from rest_framework.schemas.openapi import AutoSchema


User = get_user_model()
def redirect_view(request):
	return redirect("/tasklist")

class TodolistViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all().order_by('-id')
    serializer_class = TodoSerializer
    filterset_class =  TodoFilterSet

    schema = AutoSchema(
        tags=['Tasks'],
        component_name='Task',
        operation_id_base='Task',
    )

class MyModelListView(ListView):
    model = Task
    template_name = 'todo_list.html'

class MyModelUpdateView(UpdateView):
    model = Task
    fields = [
        'name',
        'dead_line',
        'parent_task',
        'user',
        'status',
        'sprint'
    ]
    object_list = Task.objects.all().order_by('id')
    template_name = 'todo_update_form.html'
    success_url = '/tasklist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = TaskStatus.objects.all()
        context['users'] = User.objects.all()
        context['sprints'] = Sprint.objects.all().order_by('name')
        return context

class MyModelCreateView(CreateView):
    model = Task
    fields = [
        'name',
        'dead_line',
        'parent_task',
        'user',
        'status'
    ]
    template_name = 'todo_create_form.html'
    success_url = '/tasklist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = TaskStatus.objects.all()
        context['users'] = User.objects.all()
        return context

class MyModelDeleteView(DeleteView):
    model = Task
    template_name = 'todo_delete_form.html'
    success_url = '/tasklist/'

class MyModelDetailView(DetailView):
    model = Task
    template_name = 'todo_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
class SprintListView(ListView):
    model = Sprint
    template_name = 'sprint_list.html'

class SprintUpdateView(UpdateView):
    model = Sprint
    fields = [
        'name',
        'is_active',
        'dead_line',
        'project'
    ]
    object_list = Sprint.objects.all().order_by('created')
    template_name = 'sprint_update_form.html'
    success_url = '/sprintlist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all().order_by('name')
        return context

class SprintCreateView(CreateView):
    model = Sprint
    fields = [
        'name',
        'dead_line',
    ]
    template_name = 'sprint_create_form.html'
    success_url = '/sprintlist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all()
        return context

class SprintDeleteView(DeleteView):
    model = Sprint
    template_name = 'sprint_delete_form.html'
    success_url = '/sprintlist/'

class SprintDetailView(DetailView):
    model = Sprint
    template_name = 'sprint_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
class ProjectListView(ListView):
    model = Project
    template_name = 'project_list.html'

class ProjectUpdateView(UpdateView):
    model = Project
    fields = [
        'name',
    ]
    object_list = Project.objects.all().order_by('created')
    template_name = 'project_update.html'
    success_url = '/projectlist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sprint'] = Task.objects.all().order_by('name')
        return context

class ProjectCreateView(CreateView):
    model = Project
    fields = [
        'name',
    ]
    template_name = 'project_create.html'
    success_url = '/projectlist/'

class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'project_delete.html'
    success_url = '/projectlist/'

class ProjectDetailView(DetailView):
    model = Project
    template_name = 'project_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

taskmanager/templates/project_create.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Создать проект</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Имя</span>
            <input type="text" class="form-control" placeholder="Введите имя" aria-label="Имя" aria-describedby="basic-addon1" name="name" id="id_name">
        </div>
        <div class="btn-group" role="group" aria-label="Группа кнопок по умолчанию">
            <button type="submit" class="btn btn-outline-success" value="Save">Сохранить</button>
            <button type="reset" class="btn btn-outline-warning" value="Reset">Сброс</button>
            <a class="btn btn-outline-danger" href="../projectlist/">Отмена</a>
        </div>
    </form>
</div>
{% endblock %}

taskmanager/templates/project_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Удаление проекта</h5>
</div>
<div class="container pt-2">
    <div class="alert alert-danger" role="alert">
        Вы действительно хотите удалить проект?
    </div>
    <form method="post">{% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Имя</span>
            <input type="text" class="form-control" placeholder="{{ object.name }}" aria-label="Имя" aria-describedby="basic-addon1" id="disabledInput" disabled>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Дата создания</span>
            <input type="text" class="form-control" placeholder="{{ object.created|date:"Y-m-d H:i" }}" aria-label="Дата создания" aria-describedby="basic-addon2" id="disabledInput" disabled>
        </div>
        {{ form }}
        <div class="btn-group py-5" role="group">
            <input class="btn btn-outline-danger" type="submit" value="Удалить">
            <a class="btn btn-outline-warning" href="../projectupdate/{{ object.id }}">Редактировать</a>
            <a class="btn btn-outline-success" href="../projectlist/">Сброс</a>
        </div>
    </form>
</div>  
{% endblock %}

taskmanager/templates/sprint_create_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Создать спринт</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Имя</span>
            <input type="text" class="form-control" placeholder="Введите имя" aria-label="Имя" aria-describedby="basic-addon1" name="name" id="id_name">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Дата окончания</span>
            <input type="date" value="now" name="dead_line" id="id_dead_line" class="form-control form-control-sm" aria-describedby="basic-addon2">
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.project.id_for_label }}">Проект</label>
            <select class="form-select" id="id_project" name="project">
                <option selected value="">--------</option>
                {% for project_ in projects %}
                    <option value="{{ project_.id }}">{{ project_.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="btn-group" role="group" aria-label="Группа кнопок по умолчанию">
            <button type="submit" class="btn btn-outline-success" value="Save">Сохранить</button>
            <button type="reset" class="btn btn-outline-warning" value="Reset">Сброс</button>
            <a class="btn btn-outline-danger" href="../projectlist/">Отмена</a>
        </div>
    </form>
    <script>
        document.getElementById('id_dead_line').valueAsDate = new Date();
    </script>
</div>
{% endblock %}

taskmanager/templates/sprint_delete_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Удаление спринта</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}
        <div class="alert alert-danger" role="alert">
            Вы действительно хотите удалить спринт?
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Имя</span>
            <input type="text" class="form-control" placeholder="{{ object.name }}" aria-label="Имя" aria-describedby="basic-addon1" id="disabledInput" disabled>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Дата окончания</span>
            <input type="date" name="dead_line" id="id_dead_line" class="form-control form-control-sm" value='{{ object.dead_line|date:"Y-m-d" }}' aria-describedby="basic-addon2" disabled>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon3">Дата создания</span>
            <input type="datetime-local" name="created" id="id_created" class="form-control form-control-sm" value='{{ object.created|date:"Y-m-d H:i" }}' aria-describedby="basic-addon3" disabled>
        </div>
        {{ form }}
        <div class="btn-group py-5" role="group">
            <input class="btn btn-outline-danger" type="submit" value="Удалить">
            <a class="btn btn-outline-warning" href="../sprintupdate/{{ object.id }}">Редактировать</a>
            <a class="btn btn-outline-success" href="../sprintlist/">Сброс</a>
        </div>
    </form>
</div>  
{% endblock %}

taskmanager/templates/sprint_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Просмотр спринта</h5>
</div>
<div class="container pt-2">
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Имя</span>
        <input type="text" class="form-control" placeholder="{{ object.name }}" aria-label="Имя" aria-describedby="basic-addon1" id="disabledInput" disabled>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon2">Дата окончания</span>
        <input type="date" name="dead_line" id="id_dead_line" class="form-control form-control-sm" value='{{ object.dead_line|date:"Y-m-d" }}' aria-describedby="basic-addon2" disabled>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon3">Дата создания</span>
        <input type="datetime-local" name="created" id="id_created" class="form-control form-control-sm" value='{{ object.created|date:"Y-m-d H:i" }}' aria-describedby="basic-addon3" disabled>
    </div>
    {% if object.complete_time %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon4">Дата завершения</span>
            <input type="datetime-local" name="complete_time" id="id_complete_time" class="form-control form-control-sm" value='{{ object.complete_time|date:"Y-m-d H:i" }}' aria-describedby="basic-addon4" disabled>
        </div>
    {% endif %}
    <div class="form-check form-switch pt-1">
        <input class="form-check-input" type="checkbox" role="switch" name="is_active" id="id_is_active"
        {% if object.is_active %}
        checked
        {% endif %} disabled/>
        <label class="form-lable" for="{{ object.is_active.id_for_label }}">Активность спринта</label>
    </div>
        <label class="form-label">Задачи:</label>
        <ol class="list-group">
        {% for item_ in object.sprint_tasks.all %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ item_.name }}</div>
                    Deadline: {{ item_.dead_line|date:"d.m.Y" }}
                </div>
            </li>
        {% empty %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">Нет созданных задач для этого спринта</div>
                </div>
            </li>
        {% endfor %}
        </ol>
        <div class="btn-group py-5" role="group">
            <a class="btn btn-outline-danger" href="../sprintdelete/{{ object.id }}">Удалить</a>
            <a class="btn btn-outline-warning" href="../sprintupdate/{{ object.id }}">Редактировать</a>
            <a class="btn btn-outline-success" href="../sprintlist/">Сброс</a>
        </div>
    </div>
</div>
{% endblock %}

taskmanager/templates/todo_create_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Создать задачу</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Имя</span>
            <input type="text" class="form-control" placeholder="Введите имя" aria-label="Имя" aria-describedby="basic-addon1" name="name" id="id_name">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Дата окончания</span>
            <input type="date" value="now" name="dead_line" id="id_dead_line" class="form-control form-control-sm" aria-describedby="basic-addon2">
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.parent_task.id_for_label }}">Родительская задача</label>
            <select class="form-select" id="id_parent_task" name="parent_task">
                <option selected value="">Нет задач</option>
            </select>
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.user.id_for_label }}">Исполнитель</label>
            <select class="form-select" id="id_user" name="user">
                <option selected value="">Пользователь не выбран</option>
                {% for user_ in users %}
                    <option value="{{ user_.id }}">{{ user_.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.status.id_for_label }}">Статус</label>
            <select class="form-select" id="id_status" name="status">
                <option selected value="">--------</option>
                {% for status_ in statuses %}
                    <option value="{{ status_.id }}">{{ status_.status }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="btn-group" role="group" aria-label="Группа кнопок по умолчанию">
            <button type="submit" class="btn btn-outline-success" value="Save">Сохранить</button>
            <button type="reset" class="btn btn-outline-warning" value="Reset">Сброс</button>
            <a class="btn btn-outline-danger" href="../tasklist/">Отмена</a>
        </div>
    </form>
    <script>
        document.getElementById('id_dead_line').valueAsDate = new Date();
    </script>
</div>
{% endblock %}

taskmanager/templates/todo_delete_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Удаление задачи</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}
        <div class="alert alert-danger" role="alert">
            Вы действительно хотите удалить задачу?
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Имя</span>
            <input type="text" class="form-control" placeholder="{{ object.name }}" aria-label="Имя" aria-describedby="basic-addon1" id="disabledInput" disabled>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Дата окончания</span>
            <input type="date" name="dead_line" id="id_dead_line" class="form-control form-control-sm" value='{{ object.dead_line|date:"Y-m-d" }}' aria-describedby="basic-addon2" disabled>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon3">Дата создания</span>
            <input type="datetime-local" name="created" id="id_created" class="form-control form-control-sm" value='{{ object.created|date:"Y-m-d H:i" }}' aria-describedby="basic-addon3" disabled>
        </div>
        {{ form }}
        <div class="btn-group py-5" role="group">
            <input class="btn btn-outline-danger" type="submit" value="Удалить">
            <a class="btn btn-outline-warning" href="../taskupdate/{{ object.id }}">Редактировать</a>
            <a class="btn btn-outline-success" href="../tasklist/">Сброс</a>
        </div>
    </form>
</div>  
{% endblock %}

taskmanager/templates/todo_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Просмотр задачи</h5>
</div>
<div class="container pt-2">
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Имя</span>
        <input type="text" class="form-control" placeholder="{{ object.name }}" aria-label="Имя" aria-describedby="basic-addon1" id="disabledInput" disabled>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon2">Дата окончания</span>
        <input type="date" name="dead_line" id="id_dead_line" class="form-control form-control-sm" value='{{ object.dead_line|date:"Y-m-d" }}' aria-describedby="basic-addon2" disabled>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon3">Дата создания</span>
        <input type="datetime-local" name="created" id="id_created" class="form-control form-control-sm" value='{{ object.created|date:"Y-m-d H:i" }}' aria-describedby="basic-addon3" disabled>
    </div>
    {% if object.complete_time %}
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon4">Дата завершения</span>
        <input type="datetime-local" name="complete_time" id="id_complete_time" class="form-control form-control-sm" value='{{ object.complete_time|date:"Y-m-d H:i" }}' aria-describedby="basic-addon4" disabled>
    </div>
    {% endif %}
    {% if object.parent_task %}
        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ object.parent_task.id_parent_task }}">Родительская задача</label>
            <p>{{ object.parent_task.name }}</p>
        </div>
    {% endif %}
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Исполнитель</span>
        <input type="text" class="form-control" placeholder="{{ object.user.username }}" aria-label="Исполнитель" aria-describedby="basic-addon1" id="disabledInput" disabled>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Статус</span>
        <input type="text" class="form-control" placeholder="{{ object.status.status }}" aria-label="Исполнитель" aria-describedby="basic-addon1" id="disabledInput" disabled>
    </div>
        <div class="btn-group py-5" role="group">
            <a class="btn btn-outline-danger" href="../taskdelete/{{ object.id }}">Удалить</a>
            <a class="btn btn-outline-warning" href="../taskupdate/{{ object.id }}">Редактировать</a>
            <a class="btn btn-outline-success" href="../tasklist/">Сброс</a>
        </div>
    </div>
</div>
{% endblock %}

taskmanager/templates/todo_update_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Обновление задачи</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}
        <div class="mb-3">
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">Имя</span>
                <input type="text" class="form-control" placeholder="Введите имя" aria-label="Имя" aria-describedby="basic-addon1" name="name" id="id_name" value="{{ form.name.value }}">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon2">Дата окончания</span>
                <input type="date" name="dead_line" id="id_dead_line" class="form-control form-control-sm" value='{{ object.dead_line|date:"Y-m-d" }}' aria-describedby="basic-addon2">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon3">Родительская задача</span>
                <select class="form-select" id="id_parent_task" name="parent_task" aria-describedby="basic-addon3">
                    {% if object.parent_task %}
                        <option selected value="{{ object.parent_task.id }}">{{ object.parent_task.name }}</option>
                        <option value="">Нет задач</option>
                    {% else %}
                        <option selected value="">Нет задач</option>
                    {% endif %}
                </select>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon4">Исполнитель</span>
                <select class="form-select" id="id_user" name="user" aria-describedby="basic-addon4">
                    {% if object.user %}
                        <option selected value="{{ object.user.id }}">{{ object.user.username }}</option>
                        <option value="">Пользователь не выбран</option>
                    {% else %}
                        <option selected value="">Пользователь не выбран</option>
                    {% endif %}
                    {% for user_ in users %}
                        <option value="{{ user_.id }}">{{ user_.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon5">Статус</span>
                <select class="form-select" id="id_status" name="status" aria-describedby="basic-addon5">
                    {% if object.status %}
                        <option selected value="{{ object.status.id }}">{{ object.status.status }}</option>
                        <option value="">--------</option>
                    {% else %}
                        <option selected value="">--------</option>
                    {% endif %}
                    {% for item_ in statuses %}
                        <option value="{{ item_.id }}">{{ item_.status }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon6">Спринт</span>
                <select class="form-select" id="id_sprint" name="sprint" aria-describedby="basic-addon6">
                    {% if object.sprint %}
                        <option selected value="{{ object.sprint.id }}">{{ object.sprint.name }}</option>
                        <option value="">--------</option>
                    {% else %}
                        <option value="">--------</option>
                    {% endif %}
                    {% for item_ in sprints %}
                        <option value="{{ item_.id }}">{{ item_.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="btn-group" role="group" aria-label="Группа кнопок по умолчанию">
                <button type="submit" class="btn btn-outline-success" value="Save">Сохранить</button>
                <button type="reset" class="btn btn-outline-warning" value="Reset">Сброс</button>
                <a class="btn btn-outline-danger" href="../tasklist/">Отмена</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}